### ISSUE TITLE
problem with Sanshoku doujin

### ISSUE THREAD

**Issue by Esse78** [FluffyStuff/OpenRiichi#10]
It is not always counted

![photo_2018-03-21_17-48-58](https://user-images.githubusercontent.com/18707433/37726213-2513a08a-2d35-11e8-8902-01aec4365c98.jpg)

**Comment by FluffyStuff** [comment]
I'll look into it.

**Comment by FluffyStuff** [comment]
The newest [release](https://github.com/FluffyStuff/OpenRiichi/releases) fixes the issue.
