### ISSUE TITLE
graphical glitch

### ISSUE THREAD

**Issue by Sleijen** [FluffyStuff/OpenRiichi#27]
Setup: 
We have 3 pc's at home where 2 of them show this graphical glitch in the game
specs of one of the pc with the issue:
Intel i7-3770k
radeon RX580 (radeon software version 20.4.2)
Windows 10 pro 1903
Shows glitch as seen in attached gif

the only diffrence is that the working pc has a nvidia gfx card 

I tried the following to see if i could fix the issue:
tried all settings the game has to offer including fullscreen
updated drivers
made sure radeon settings werent messing with the game
tried windows compatibility mode.

![OpenRiichi3](https://user-images.githubusercontent.com/64754834/80927041-7a541700-8d9b-11ea-9ef6-7ce4dbd36ad8.gif)

**Comment by FluffyStuff** [comment]
I was able to reproduce the issue on an AMD card. I'll take a look at this as soon as possible.

**Comment by FluffyStuff** [comment]
This should now be fixed with [v0.2.1.1](https://github.com/FluffyStuff/OpenRiichi/releases/tag/v0.2.1.1).
