### ISSUE TITLE
Use git subtree to include Engine repo

### ISSUE THREAD

**Issue by tpenguinltg** [FluffyStuff/OpenRiichi#4]
Since the Engine repo is an explicit dependency of this repo, it should be included in the repo as a git subtree (or perhaps a git submodule). If that's done, the Makefile can instead reference an Engine folder in the repo instead of relying on the user to manually clone the other repo and mandating that it's cloned in ../Engine. This would also make it easier to clean up because one would only have to delete this repo's folder instead of the folders for this repo and Engine.

**Comment by FluffyStuff** [comment]
I went with a git submodule. It seemed to make more sense, since I'm frequently pushing changes to the Engine repo.

PS: I'm pretty sure I just unlocked an achievement in procrastination, by waiting over 3 years to do something that literally took less than 5 minutes to do...
