### ISSUE TITLE
sequential melds have the sideways tile placed in the wrong spot

### ISSUE THREAD

**Issue by logarrhythmic** [FluffyStuff/OpenRiichi#6]
![image](https://cloud.githubusercontent.com/assets/1952758/22766707/b66186f6-ee7f-11e6-9467-668c4f684c76.png)
The called tile should always be on the left, instead of having the tiles be in order like this. See http://arcturus.su/wiki/Chii#Chii

**Comment by stephini** [comment]
My understanding was that you have them sequential and the chii'd tile is tilted since you don't need to indicate who you chii'd from since you can only chii from the previous player.

**Comment by FluffyStuff** [comment]
Either way is actually valid. But it's true that tenhou does it in the non-sequential way.
I changed it to the tenhou way in the development build.

**Comment by FluffyStuff** [comment]
This is now in the release build.
