### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Esse78** [FluffyStuff/OpenRiichi#8]
I can't compile in windows can you help me

**Comment by polarina** [comment]
What is problem you're experiencing? What error messages are you seeing?

**Comment by Esse78** [comment]
I'm not able to compilate
could you pleas send to me a copiled version for windows

2017-05-05 19:39 GMT+02:00 Gabríel Arthúr Pétursson <
notifications@github.com>:

**Comment by polarina** [comment]
What steps have you tried in order to compile the program? Did you get any error messages, and if so, what are they?

**Comment by Esse78** [comment]
first in the Makefile you don't have WindowsRelease you only have windows
after I do "make windows" I recive thouse errors

Compilation failed: 6 error(s), 0 warning(s)
../Engine/Properties/Mat4.vala:10.9-16.9: error: use `new' operator to
create new objects
../Engine/Properties/Quat.vala:33.9-33.39: error: use `new' operator to
create new objects
        from_euler(vec.x, vec.y, vec.z);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../Engine/Properties/Mat3.vala:9.9-14.9: error: use `new' operator to
create new objects
source/Game/Logic/IGameConnection.vala:159.47-159.58: error: Property
`GameLocalConnection.authoritative' with private accessor cannot be marked
as abstract, virtual or override
    public override bool authoritative { get; private set; }
                                              ^^^^^^^^^^^^
source/Game/Logic/IGameConnection.vala:98.47-98.58: error: Property
`GameNetworkConnection.authoritative' with private accessor cannot be
marked as abstract, virtual or override
    public override bool authoritative { get; private set; }
                                              ^^^^^^^^^^^^
source/Game/Logic/IGameConnection.vala:187.47-187.58: error: Property
`TunneledGameConnection.authoritative' with private accessor cannot be
marked as abstract, virtual or override
    public override bool authoritative { get; private set; }
                                              ^^^^^^^^^^^^
make: *** [Makefile:75: windows] Error 1



2017-05-05 19:49 GMT+02:00 Gabríel Arthúr Pétursson <
notifications@github.com>:

**Comment by FluffyStuff** [comment]
The Vala dev team released a slightly backwards compatibility breaking release. The newest release on the master branch fixes this issue. Also, you can find prebuilt binaries [here](https://github.com/FluffyStuff/OpenRiichi/releases).

**Comment by Esse78** [comment]
thank you and sorry for the trouble

2017-05-06 5:06 GMT+02:00 Kristján Árni Gerhardsson <
notifications@github.com>:

**Comment by FluffyStuff** [comment]
No problem. Thanks for pointing out the issue.
